sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t docker-react-01 -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react-01 npm run test